R CMD INSTALL --build \
/tmp/packages/fastmap_1.1.0.tar.gz \
/tmp/packages/sys_3.4.tar.gz \
/tmp/packages/bit_4.0.4.tar.gz \
/tmp/packages/bitops_1.0-7.tar.gz \
/tmp/packages/formatR_1.12.tar.gz \
/tmp/packages/plogr_0.2.0.tar.gz \
/tmp/packages/png_0.1-7.tar.gz \
/tmp/packages/curl_4.3.2.tar.gz \
/tmp/packages/jsonlite_1.8.0.tar.gz \
/tmp/packages/mime_0.12.tar.gz \
/tmp/packages/colorspace_2.0-3.tar.gz \
/tmp/packages/crayon_1.5.1.tar.gz \
/tmp/packages/utf8_1.2.2.tar.gz \
/tmp/packages/GenomeInfoDbData_1.2.7.tar.gz \
/tmp/packages/zlibbioc_1.40.0.tar.gz \
/tmp/packages/matrixStats_0.61.0.tar.gz \
/tmp/packages/futile.options_1.0.1.tar.gz \
/tmp/packages/DBI_1.1.2.tar.gz \
/tmp/packages/XML_3.99-0.9.tar.gz \
/tmp/packages/xtable_1.8-4.tar.gz \
/tmp/packages/farver_2.1.0.tar.gz \
/tmp/packages/labeling_0.4.2.tar.gz \
/tmp/packages/R6_2.5.1.tar.gz \
/tmp/packages/viridisLite_0.4.0.tar.gz \
/tmp/packages/fansi_1.0.3.tar.gz \
/tmp/packages/magrittr_2.0.3.tar.gz \
/tmp/packages/pkgconfig_2.0.3.tar.gz \
/tmp/packages/snow_0.4-4.tar.gz \
/tmp/packages/BH_1.78.0-0.tar.gz \
/tmp/packages/RColorBrewer_1.1-3.tar.gz \
/tmp/packages/digest_0.6.29.tar.gz \
/tmp/packages/glue_1.6.2.tar.gz \
/tmp/packages/gtable_0.3.0.tar.gz \
/tmp/packages/isoband_0.2.5.tar.gz \
/tmp/packages/rlang_1.0.2.tar.gz \
/tmp/packages/withr_2.5.0.tar.gz \
/tmp/packages/BiocGenerics_0.40.0.tar.gz \
/tmp/packages/locfit_1.5-9.5.tar.gz \
/tmp/packages/Rcpp_1.0.8.3.tar.gz \
/tmp/packages/BiocVersion_3.14.0.tar.gz \
/tmp/packages/cachem_1.0.6.tar.gz \
/tmp/packages/askpass_1.1.tar.gz \
/tmp/packages/bit64_4.0.5.tar.gz \
/tmp/packages/cli_3.2.0.tar.gz \
/tmp/packages/RCurl_1.98-1.6.tar.gz \
/tmp/packages/lambda.r_1.2.4.tar.gz \
/tmp/packages/lifecycle_1.0.1.tar.gz \
/tmp/packages/munsell_0.5.0.tar.gz \
/tmp/packages/ellipsis_0.3.2.tar.gz \
/tmp/packages/MatrixGenerics_1.6.0.tar.gz \
/tmp/packages/S4Vectors_0.32.4.tar.gz \
/tmp/packages/Biobase_2.54.0.tar.gz \
/tmp/packages/RcppArmadillo_0.11.0.0.0.tar.gz \
/tmp/packages/memoise_2.0.1.tar.gz \
/tmp/packages/openssl_2.0.0.tar.gz \
/tmp/packages/vctrs_0.4.0.tar.gz \
/tmp/packages/futile.logger_1.4.3.tar.gz \
/tmp/packages/scales_1.1.1.tar.gz \
/tmp/packages/IRanges_2.28.0.tar.gz \
/tmp/packages/blob_1.2.2.tar.gz \
/tmp/packages/httr_1.4.2.tar.gz \
/tmp/packages/pillar_1.7.0.tar.gz \
/tmp/packages/GenomeInfoDb_1.30.1.tar.gz \
/tmp/packages/XVector_0.34.0.tar.gz \
/tmp/packages/DelayedArray_0.20.0.tar.gz \
/tmp/packages/BiocParallel_1.28.3.tar.gz \
/tmp/packages/Biostrings_2.62.0.tar.gz \
/tmp/packages/RSQLite_2.2.12.tar.gz \
/tmp/packages/tibble_3.1.6.tar.gz \
/tmp/packages/GenomicRanges_1.46.1.tar.gz \
/tmp/packages/KEGGREST_1.34.0.tar.gz \
/tmp/packages/SummarizedExperiment_1.24.0.tar.gz \
/tmp/packages/ggplot2_3.3.5.tar.gz \
/tmp/packages/AnnotationDbi_1.56.2.tar.gz \
/tmp/packages/annotate_1.72.0.tar.gz \
/tmp/packages/genefilter_1.76.0.tar.gz \
/tmp/packages/geneplotter_1.72.0.tar.gz \
/tmp/packages/DESeq2_1.34.0.tar.gz \
